export const SET_TEXT_STATUS = 'SET_TEXT_STATUS'
export const SET_FORM_STATUS = 'SET_FORM_STATUS'
export const RESET_FORM_STATUS = 'RESET_FORM_STATUS'
export const SUBMIT_FORM = 'SUBMIT_FORM'

export const SET_REVIEWS = 'SET_REVIEWS'
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const REFETCH_REVIEWS = 'REFETCH_REVIEWS'
